debug_mode: true
log_to_file: logs/elastix_log_20251111_185648.txt
log_to_console: true
registration_method: bspline
demons_iterations: 200
transform_type: BSplineTransform
grid_spacing: 64
bspline_transform_spline_order: 3
bspline_interpolation_order: 3
final_bspline_interpolation_order: 3
use_cyclic_transform: true
metric: AdvancedMeanSquares
number_of_histogram_bins: 32
number_of_fixed_histogram_bins: 32
number_of_moving_histogram_bins: 32
optimizer: AdaptiveStochasticGradientDescent
max_iterations: 500
step_size: 0.6
sp_a: 50.0
auto_parameter_estimation: true
auto_scales_estimation: true
pyramid_levels: 3
fixed_image_pyramid: FixedSmoothingImagePyramid
moving_image_pyramid: MovingSmoothingImagePyramid
pyramid_schedule: 8 8 4 4 2 2 1 1
sampler: RandomCoordinate
spatial_samples: 5000
max_sampling_attempts: 4
new_samples_every_iteration: true
check_number_of_samples: true
use_normalization: false
sp_a_stage2: 400.0
sp_alpha_stage2: 0.602
fixed_limit_range_ratio: 0.01
moving_limit_range_ratio: 0.01
fixed_kernel_bspline_order: 0
moving_kernel_bspline_order: 3
use_fast_and_low_memory: true
use_jacobian_preconditioning: true
finite_difference_derivative: true
write_result_image: true
write_transform_parameters_each_iteration: false
write_transform_parameters_each_resolution: false
